version: "3"
services:
  boonbot:
    build: .
    restart: always
    environment:
      - TOKEN=${TOKEN}
      - GUILD_ID=${GUILD_ID}
      - BOT_CHANNEL_ID=${BOT_CHANNEL_ID}
      - CONTESTS_IDS=${CONTESTS_IDS}
      - TEAM_IDS=${TEAM_IDS}
      - TEAM_NAMES=${TEAM_NAMES}
