name: python format
on:
  - push
  - pull_request
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run black
        uses: rickstaa/action-black@v1
        id: run_black
        with:
          black_args: "."
      - name: commit changes
        if: steps.run_black.outputs.is_formatted == 'true'
        uses: EndBug/add-and-commit@v9
        with:
          message: 'style: Format with Black'
          default_author: github_actions